I have added a responsive desktop version to the mobile version so that user can use it with any device
ndikumanaisaie/portfolio_ndikumana pull request #5
Opened 2022-04-28 09:08 UTC by ndikumanaisaie

This branch contains the desktop version which is responsive to many devices, smart phones of different size, tablets and big screens.

2022-04-28 11:26 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @ndikumanaisaie, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Good git-flow
✔️ Professional Readme
✔️ Good job on implementing the desktop version so far

## Required 
- [ ] Kindly edit your readme by adding your contact information and social media links and also a description for the project as it shows who worked on the repo and what you have worked on.
- [ ] It would be better to replace your Pull request title as it looks like a sentence. The Pull Request title should be in words like " Portfolio:  Desktop Version ".
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 11:26 UTC, sja-thedude commented on index.html
> +              <span class="greater-than"><i class="fa-solid fa-angle-right"></i></span>
Desktop Version:
- [ ] Kindly follow spacing for the About myself section by giving more spacing to the left side as per the Figma design.
- [ ] Kindly follow the font weight for the list as shown in the attached video.
- [ ] Kindly reduce the space below the "About Myself" title as per the figma design.

https://user-images.githubusercontent.com/70269507/165737871-b685c2b5-3c9e-41cc-a6c2-c3d742e61482.mov

2022-04-28 11:26 UTC, sja-thedude commented on index.html
> +              <span >Frameworks</span>
- [ ] Kindly make sure to follow the Figma design for the languages lists for the mobile version.
- [ ] Kindly make sure to follow the correct background image for the contact section of the mobile version as per the Figma design.

https://user-images.githubusercontent.com/70269507/165738524-7a012206-e138-4795-8cc2-0be15a272f8a.mov

2022-04-28 11:26 UTC, sja-thedude commented on index.html
> -          <a href="#"><img src="./images/Union.svg" alt="more"></a>
- [ ] Kindly avoid removing this code as it's for the mobile version to display the hamburger. You have to disable this in the desktop version with CSS.

2022-04-28 15:04 UTC, ndikumanaisaie commented
Hi!

Thank you for your CR,

Please tell me if i have to duplicate code to add mobile images, content
and backgrounds because they are different from that of desktop version.

On Thu, Apr 28, 2022, 12:26 Syeda Juveria Afreen ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Required Changes ♻️
>
> Hi @ndikumanaisaie <https://github.com/ndikumanaisaie>, This is
> @sja-thedude <https://github.com/sja-thedude> your code reviewer.
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: 768070f3-bc9a-4aba-b8bc-25793e00ea1e_text]
> <https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif>
> Highlights
>
> ✔️ Good git-flow
> ✔️ Professional Readme
> ✔️ Good job on implementing the desktop version so far
> Required
>
>    - Kindly edit your readme by adding your contact information and
>    social media links and also a description for the project as it shows who
>    worked on the repo and what you have worked on.
>    - It would be better to replace your Pull request title as it looks
>    like a sentence. The Pull Request title should be in words like "
>    Portfolio: Desktop Version ".
>    - *Check the comments under the review.*
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me ***@***.*** <https://github.com/sja-thedude>]
> in your question so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In portfolio.css
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#discussion_r860719731>
> :
>
> > +    padding: 100px 150px 0;
>
> +  }
>
> +}
>
> +
>
> ***@***.*** screen and (min-width: 768px) and (max-width: 1024px) {
>
> +  .header-bg {
>
> +    padding: 100px 100px 0;
>
> +  }
>
> +
>
> +  .card-work {
>
> +    display: flex;
>
> +    flex-direction: column;
>
> +  }
>
> +}
>
> +
>
> ***@***.*** screen and (min-width: 501px) and (max-width: 767px) {
>
>
>
>    - Kindly remove the media query as it's not required. Media queries
>    should only be used for desktop versions, not mobile ones.
>
> ------------------------------
>
> In portfolio.css
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#discussion_r860719885>
> :
>
> > +  .header-bg {
>
> +    padding: 100px 20px 0;
>
> +  }
>
> +
>
> +  .card-work {
>
> +    display: flex;
>
> +    flex-direction: column;
>
> +  }
>
> +
>
> +  .about {
>
> +    display: flex;
>
> +    flex-direction: column;
>
> +  }
>
> +}
>
> +
>
> ***@***.*** screen and (max-width: 500px) {
>
>
>
>    - Kindly remove the media query as it's not required. Media queries
>    should only be used for desktop versions, not mobile ones.
>
> ------------------------------
>
> In index.html
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#discussion_r860736376>
> :
>
> > +        <div class="menu">
>
> +          <a href="#"><span class="my-logo">Portfolio</span></a>
>
> +          <a href="#"><span class="my-logo">About</span></a>
>
> +          <a href="#"><span class="my-logo">Contact</span></a>
>
>          </div>
>
>        </nav>
>
>      </header>
>
> -    <div class="header-background-mobile">
>
> -      <div class="primary-text">
>
> -        <h1>I'm ndikumana Isaie to see you</h1>
>
> -      </div>
>
> +    <div class="header-bg">
>
> +
>
> +      <h1>I'm ndikumana <br> Isaie to see you</h1>
>
>
> Mobile version:
>
>    - Kindly make sure that the hamburger icon is displayed for the mobile
>    version as per the Figma design.
>    - Kindly add spacing after the social media icons as per the Figma
>    design.
>
>
> https://user-images.githubusercontent.com/70269507/165733663-3fec9171-7a4b-4eb4-b27a-cf25e50e46d8.mov
>
> Desktop Version:
>
>    - Kindly reduce the extra spacing on the right as shown in the
>    attached image. Make sure to follow the Figma design.
>
> [image: Screenshot 2022-04-28 at 1 20 11 PM]
> <https://user-images.githubusercontent.com/70269507/165734253-32e92a04-10bf-4df6-913d-bcc7324c8e95.png>
> ------------------------------
>
> In index.html
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#discussion_r860739163>
> :
>
> >            </p>
>
>            <ul>
>
>              <li><a href="#">html</a></li>
>
>              <li><a href="#">css</a></li>
>
>              <li><a href="#">javascript</a></li>
>
>            </ul>
>
> -          <div class="action">
>
> -            <p>See Project</p>
>
> -          </div>
>
> +          <p class="action">See Project</p>
>
>
>
>    - Kindly add the button interactions (hover, active, pressed) for all
>    the buttons in the portfolio as per the Figma design.
>
> [image: Screenshot 2022-04-28 at 1 22 45 PM]
> <https://user-images.githubusercontent.com/70269507/165734805-1767b5f0-d9a5-4a59-a98d-f21884387100.png>
> ------------------------------
>
> In index.html
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#discussion_r860741899>
> :
>
> > +          <img src="./images/Snapshoot-Portfolio2.png" alt="card-work">
>
>          </div>
>
> -        <div class="left-block">
>
> +        <div class="left-block left-block1">
>
>            <h2 class="h2">
>
> -            Tonic
>
> +            Facebook 360
>
>            </h2>
>
>            <div class="frame1">
>
> -            <p>conopy</p>
>
> +            <p class="c">FACEBOOK</p>
>
>              <img src="./images/Counter.png" alt="">
>
> -            <p class="p1">Back End Dev</p>
>
> +            <p class="p1">Full Stack Dev</p>
>
>              <img src="./images/Counter.png" alt="">
>
>              <p class="p1">2020</p>
>
>            </div>
>
>            <p class="primary1">
>
> -            A daily selection of privately personalized reads;
>
> -            no accounts or sign-ups required.
>
> +            Exploring the future of media in Facebook's first Virtual Reality app;
>
> +            a place to discover and enjoy 360 photos and videos on Gear VR.
>
>
> Mobile Version:
>
>    - Kindly make sure to follow all the images as given for all the cards
>    in the mobile version.
>    - Kindly make sure to display the cards correctly as per the Figma
>    design where images are displayed first and then the content for all the
>    cards.
>    - Kindly make sure to align the button text correctly as per the
>    design.
>
>
> https://user-images.githubusercontent.com/70269507/165735215-cfb04141-61bb-48c0-91a6-d87178b54c9f.mov
>
> Desktop Version:
>
>    - Kindly make sure to reduce the extra spacing from all the cards
>
>
> https://user-images.githubusercontent.com/70269507/165736211-622510e6-4581-4a56-9002-6b1fe9e13167.mov
> ------------------------------
>
> In index.html
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#discussion_r860752980>
> :
>
> > +    <section class="contact-section">
>
> +      <div class="contact-me">
>
> +        <h2>contact me</h2>
>
> +        <p>
>
> +          If you have an application you are interested in developing,
>
> +          a feature that you need built or a project that needs coding.
>
> +    [...]

2022-04-28 15:38 UTC, sja-thedude commented
> Hi!
> 
> Thank you for your CR,
> 
> Please tell me if i have to duplicate code to add mobile images, content
> and backgrounds because they are different from that of desktop version.

Hi @ndikumanaisaie 
You have to use the same html code and create the desktop and mobile version from it. You have to use css to display elements for both.
The elements which are not present in a specific version you have to use display: none for it. Which will make that specific part disappear. Example: For hamburger to disappear on desktop you have to use display: none inside the media query.

Basically you have to layout the elements with respect to the version with css.

2022-04-28 16:03 UTC, ndikumanaisaie commented
Thank you for the clarification. But how can i change texts content and
images using CSS only without adding extra html code. For background images
i can see that it is possible

On Thu, Apr 28, 2022, 16:38 Syeda Juveria Afreen ***@***.***>
wrote:

> Hi!
>
> Thank you for your CR,
>
> Please tell me if i have to duplicate code to add mobile images, content
> and backgrounds because they are different from that of desktop version.
>
> Hi @ndikumanaisaie <https://github.com/ndikumanaisaie>
> You have to use the same html code and create the desktop and mobile
> version from it. You have to use css to display elements for both.
> The elements which are not present in a specific version you have to use
> display: none for it. Which will make that specific part disappear.
> Example: For hamburger to disappear on desktop you have to use display:
> none inside the media query.
>
> Basically you have to layout the elements with respect to the version with
> css.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#issuecomment-1112359327>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANB6A66ZSLQFAGBRIIFIFHTVHKWHDANCNFSM5URWOZAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-29 16:38 UTC, ndikumanaisaie commented
Hallo! Thank you. I tried hard and finaly i got it.

On Fri, Apr 29, 2022, 17:18 Khusiima Luke Masaba ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Hello @ndikumanaisaie <https://github.com/ndikumanaisaie> 👋 ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> [image: almost-there]
> <https://camo.githubusercontent.com/395b3b21a125e95f2b70c16f35342677ad5350ec23bec5d6d9db1383f2c87427/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f42504a6d74685133595277443651716356442f67697068792e676966>
> Highlights 🍾
>
>    - Linter checks passing ✔️
>    - Did most of the previous code reviewers requested changes 👍
>
> Optional suggestions 💭
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏 💻
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> [OPTIONAL]
>
>    - This may be marked as optional but please align the text in the
>    buttons to be in the right positions as seen in the Figma.
>
> Your Implentation
>
> [image: image]
> <https://user-images.githubusercontent.com/45460192/165983633-e5802f2d-bc52-4720-a7c6-714931e0be48.png>
> Figma
>
> [image: image]
> <https://user-images.githubusercontent.com/45460192/165983760-20f9149e-92b7-4024-8b63-2eae67752513.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ndikumanaisaie/portfolio_ndikumana/pull/5#pullrequestreview-957966935>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANB6A67OBNGXXB6CDSXPGDTVHQDVDANCNFSM5URWOZAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-29 16:49 UTC, Lucas-Masaba commented
Thank you for taking the time to implement that 😎

2022-05-05 07:24 UTC, closed without merging